spring.application.name=api-telemetria

# Configuração do Servidor
server.port=8080

# Configuração da Fonte de Dados (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3307/TelemetriaMotores?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=industria_user
spring.datasource.password=123@Mudar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
